// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/anomaly.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FingerprintRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FingerprintHash string                 `protobuf:"bytes,2,opt,name=fingerprint_hash,json=fingerprintHash,proto3" json:"fingerprint_hash,omitempty"`
	Ip              string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent       string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FingerprintRequest) Reset() {
	*x = FingerprintRequest{}
	mi := &file_proto_anomaly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintRequest) ProtoMessage() {}

func (x *FingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anomaly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintRequest.ProtoReflect.Descriptor instead.
func (*FingerprintRequest) Descriptor() ([]byte, []int) {
	return file_proto_anomaly_proto_rawDescGZIP(), []int{0}
}

func (x *FingerprintRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FingerprintRequest) GetFingerprintHash() string {
	if x != nil {
		return x.FingerprintHash
	}
	return ""
}

func (x *FingerprintRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FingerprintRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiskScore     float32                `protobuf:"fixed32,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Block         bool                   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_proto_anomaly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anomaly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_anomaly_proto_rawDescGZIP(), []int{1}
}

func (x *RiskResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskResponse) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

var File_proto_anomaly_proto protoreflect.FileDescriptor

const file_proto_anomaly_proto_rawDesc = "" +
	"\n" +
	"\x13proto/anomaly.proto\x12\aanomaly\"\x8d\x01\n" +
	"\x12FingerprintRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10fingerprint_hash\x18\x02 \x01(\tR\x0ffingerprintHash\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"C\n" +
	"\fRiskResponse\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x01 \x01(\x02R\triskScore\x12\x14\n" +
	"\x05block\x18\x02 \x01(\bR\x05block2P\n" +
	"\x0fAnomalyDetector\x12=\n" +
	"\aAnalyze\x12\x1b.anomaly.FingerprintRequest\x1a\x15.anomaly.RiskResponseB;Z9github.com/PickStranger/reverse-proxy-agent/internal/grpcb\x06proto3"

var (
	file_proto_anomaly_proto_rawDescOnce sync.Once
	file_proto_anomaly_proto_rawDescData []byte
)

func file_proto_anomaly_proto_rawDescGZIP() []byte {
	file_proto_anomaly_proto_rawDescOnce.Do(func() {
		file_proto_anomaly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anomaly_proto_rawDesc), len(file_proto_anomaly_proto_rawDesc)))
	})
	return file_proto_anomaly_proto_rawDescData
}

var file_proto_anomaly_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_anomaly_proto_goTypes = []any{
	(*FingerprintRequest)(nil), // 0: anomaly.FingerprintRequest
	(*RiskResponse)(nil),       // 1: anomaly.RiskResponse
}
var file_proto_anomaly_proto_depIdxs = []int32{
	0, // 0: anomaly.AnomalyDetector.Analyze:input_type -> anomaly.FingerprintRequest
	1, // 1: anomaly.AnomalyDetector.Analyze:output_type -> anomaly.RiskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_anomaly_proto_init() }
func file_proto_anomaly_proto_init() {
	if File_proto_anomaly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anomaly_proto_rawDesc), len(file_proto_anomaly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_anomaly_proto_goTypes,
		DependencyIndexes: file_proto_anomaly_proto_depIdxs,
		MessageInfos:      file_proto_anomaly_proto_msgTypes,
	}.Build()
	File_proto_anomaly_proto = out.File
	file_proto_anomaly_proto_goTypes = nil
	file_proto_anomaly_proto_depIdxs = nil
}
