// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/anomaly.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnomalyDetector_Analyze_FullMethodName = "/anomaly.AnomalyDetector/Analyze"
)

// AnomalyDetectorClient is the client API for AnomalyDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnomalyDetectorClient interface {
	Analyze(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*RiskResponse, error)
}

type anomalyDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewAnomalyDetectorClient(cc grpc.ClientConnInterface) AnomalyDetectorClient {
	return &anomalyDetectorClient{cc}
}

func (c *anomalyDetectorClient) Analyze(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, AnomalyDetector_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnomalyDetectorServer is the server API for AnomalyDetector service.
// All implementations must embed UnimplementedAnomalyDetectorServer
// for forward compatibility.
type AnomalyDetectorServer interface {
	Analyze(context.Context, *FingerprintRequest) (*RiskResponse, error)
	mustEmbedUnimplementedAnomalyDetectorServer()
}

// UnimplementedAnomalyDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnomalyDetectorServer struct{}

func (UnimplementedAnomalyDetectorServer) Analyze(context.Context, *FingerprintRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedAnomalyDetectorServer) mustEmbedUnimplementedAnomalyDetectorServer() {}
func (UnimplementedAnomalyDetectorServer) testEmbeddedByValue()                         {}

// UnsafeAnomalyDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnomalyDetectorServer will
// result in compilation errors.
type UnsafeAnomalyDetectorServer interface {
	mustEmbedUnimplementedAnomalyDetectorServer()
}

func RegisterAnomalyDetectorServer(s grpc.ServiceRegistrar, srv AnomalyDetectorServer) {
	// If the following call panics, it indicates UnimplementedAnomalyDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnomalyDetector_ServiceDesc, srv)
}

func _AnomalyDetector_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectorServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnomalyDetector_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectorServer).Analyze(ctx, req.(*FingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnomalyDetector_ServiceDesc is the grpc.ServiceDesc for AnomalyDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnomalyDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anomaly.AnomalyDetector",
	HandlerType: (*AnomalyDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _AnomalyDetector_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anomaly.proto",
}
