// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/anomaly.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RevEnvironmentConfigService_GetEnvironment_FullMethodName    = "/ai.v1.RevEnvironmentConfigService/GetEnvironment"
	RevEnvironmentConfigService_UpdateEnvironment_FullMethodName = "/ai.v1.RevEnvironmentConfigService/UpdateEnvironment"
)

// RevEnvironmentConfigServiceClient is the client API for RevEnvironmentConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevEnvironmentConfigServiceClient interface {
	GetEnvironment(ctx context.Context, in *EnvironmentRequester, opts ...grpc.CallOption) (*RevEnvironment, error)
	UpdateEnvironment(ctx context.Context, in *RevEnvironment, opts ...grpc.CallOption) (*EnvironmentUpdateResponse, error)
}

type revEnvironmentConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRevEnvironmentConfigServiceClient(cc grpc.ClientConnInterface) RevEnvironmentConfigServiceClient {
	return &revEnvironmentConfigServiceClient{cc}
}

func (c *revEnvironmentConfigServiceClient) GetEnvironment(ctx context.Context, in *EnvironmentRequester, opts ...grpc.CallOption) (*RevEnvironment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevEnvironment)
	err := c.cc.Invoke(ctx, RevEnvironmentConfigService_GetEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revEnvironmentConfigServiceClient) UpdateEnvironment(ctx context.Context, in *RevEnvironment, opts ...grpc.CallOption) (*EnvironmentUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvironmentUpdateResponse)
	err := c.cc.Invoke(ctx, RevEnvironmentConfigService_UpdateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevEnvironmentConfigServiceServer is the server API for RevEnvironmentConfigService service.
// All implementations must embed UnimplementedRevEnvironmentConfigServiceServer
// for forward compatibility.
type RevEnvironmentConfigServiceServer interface {
	GetEnvironment(context.Context, *EnvironmentRequester) (*RevEnvironment, error)
	UpdateEnvironment(context.Context, *RevEnvironment) (*EnvironmentUpdateResponse, error)
	mustEmbedUnimplementedRevEnvironmentConfigServiceServer()
}

// UnimplementedRevEnvironmentConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevEnvironmentConfigServiceServer struct{}

func (UnimplementedRevEnvironmentConfigServiceServer) GetEnvironment(context.Context, *EnvironmentRequester) (*RevEnvironment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvironment not implemented")
}
func (UnimplementedRevEnvironmentConfigServiceServer) UpdateEnvironment(context.Context, *RevEnvironment) (*EnvironmentUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvironment not implemented")
}
func (UnimplementedRevEnvironmentConfigServiceServer) mustEmbedUnimplementedRevEnvironmentConfigServiceServer() {
}
func (UnimplementedRevEnvironmentConfigServiceServer) testEmbeddedByValue() {}

// UnsafeRevEnvironmentConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevEnvironmentConfigServiceServer will
// result in compilation errors.
type UnsafeRevEnvironmentConfigServiceServer interface {
	mustEmbedUnimplementedRevEnvironmentConfigServiceServer()
}

func RegisterRevEnvironmentConfigServiceServer(s grpc.ServiceRegistrar, srv RevEnvironmentConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedRevEnvironmentConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevEnvironmentConfigService_ServiceDesc, srv)
}

func _RevEnvironmentConfigService_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvironmentRequester)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevEnvironmentConfigServiceServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevEnvironmentConfigService_GetEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevEnvironmentConfigServiceServer).GetEnvironment(ctx, req.(*EnvironmentRequester))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevEnvironmentConfigService_UpdateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevEnvironment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevEnvironmentConfigServiceServer).UpdateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevEnvironmentConfigService_UpdateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevEnvironmentConfigServiceServer).UpdateEnvironment(ctx, req.(*RevEnvironment))
	}
	return interceptor(ctx, in, info, handler)
}

// RevEnvironmentConfigService_ServiceDesc is the grpc.ServiceDesc for RevEnvironmentConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevEnvironmentConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.RevEnvironmentConfigService",
	HandlerType: (*RevEnvironmentConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnvironment",
			Handler:    _RevEnvironmentConfigService_GetEnvironment_Handler,
		},
		{
			MethodName: "UpdateEnvironment",
			Handler:    _RevEnvironmentConfigService_UpdateEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anomaly.proto",
}
